# Generated by Django 3.0.5 on 2021-01-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msd_dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=150)),
                ('text', models.TextField(max_length=1000)),
                ('language_code', models.TextField(max_length=10, null=True)),
                ('language', models.TextField(max_length=20, null=True)),
                ('type', models.TextField(max_length=20)),
            ],
        ),
    ]
