# Generated by Django 3.0.5 on 2021-01-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msd_dataset',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='language',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='language_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
