# Generated by Django 3.0.5 on 2021-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_auto_20210118_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msd_dataset',
            name='language',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='language_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
