# Generated by Django 3.0.5 on 2021-01-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_auto_20210118_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msd_dataset',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='language_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='msd_dataset',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
