# Generated by Django 3.0.5 on 2021-01-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0005_msd_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='msd_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category_actual', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('language_code', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='msd_contents',
        ),
    ]
