# Generated by Django 3.0.5 on 2021-01-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_auto_20210127_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='undetected_msd_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('header_category', models.CharField(max_length=50)),
                ('content_category', models.CharField(max_length=50)),
            ],
        ),
    ]
