# Generated by Django 3.0.5 on 2021-01-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_undetected_msd_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='undetected_msd_log',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='undetected_msd_log',
            name='language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='undetected_msd_log',
            name='language_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
