# Generated by Django 3.0.5 on 2021-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0008_auto_20210128_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='undetected_msd_log',
            name='file_name',
            field=models.TextField(default=''),
        ),
    ]
